mod commands;
mod db;
mod entities;
mod error;

use db::{init_database, AppState};
use crate::error::AppError;
use sea_orm::DatabaseConnection;
use tauri::Manager;

fn create_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            // Tables
            commands::tables::get_all_tables,
            commands::tables::create_table,
            commands::tables::delete_table,
            commands::tables::get_table_status,
            // Categories
            commands::categories::get_all_categories,
            commands::categories::create_category,
            commands::categories::update_category,
            commands::categories::delete_category,
            // Products
            commands::products::get_all_products,
            commands::products::get_products_by_category,
            commands::products::get_favorite_products,
            commands::products::search_products,
            commands::products::create_product,
            commands::products::update_product,
            commands::products::delete_product,
            // Orders
            commands::orders::get_open_order_by_table,
            commands::orders::create_order,
            commands::orders::update_order,
            commands::orders::add_order_item,
            commands::orders::update_order_item,
            commands::orders::remove_order_item,
            commands::orders::delete_order,
            commands::orders::transfer_order,
            commands::orders::merge_orders,
            commands::orders::mark_items_paid,
            commands::orders::get_order_history,
            commands::orders::get_order_details,
            // Payments
            commands::payments::create_payment,
            commands::payments::get_payments_by_order,
            // Dashboard
            commands::dashboard::get_dashboard_stats,
            commands::dashboard::get_extended_dashboard_stats,
            commands::dashboard::get_revenue_trend,
            // Admin
            commands::admin::verify_pin,
            commands::admin::check_admin_status,
            commands::admin::change_pin,
            commands::admin::set_recovery,
            commands::admin::get_recovery_question,
            commands::admin::reset_pin,
            // Expenses
            commands::expenses::create_expense,
            commands::expenses::update_expense,
            commands::expenses::get_all_expenses,
            commands::expenses::delete_expense,
            // Reports
            commands::reports::get_recent_logs,
            commands::reports::create_log,
            commands::reports::generate_zreport,
            commands::reports::get_zreport_history,
            commands::reports::get_monthly_reports,
            // Maintenance
            commands::maintenance::archive_old_data,
            commands::maintenance::vacuum_database,
            commands::maintenance::check_end_of_day,
            commands::maintenance::system_check,
            commands::maintenance::backup_database,
            commands::maintenance::backup_database_with_rotation,
            commands::maintenance::execute_end_of_day,
            commands::maintenance::export_database,
            commands::maintenance::seed_database,
            commands::maintenance::import_legacy_data,
        ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.\n"),
            "../src/renderer/src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }

            // Initialize database connection
            let app_handle = app.handle().clone();
            let app_data_dir = app_handle
                .path()
                .app_data_dir()
                .expect("Failed to get app data dir");

            // Create app data dir if needed
            std::fs::create_dir_all(&app_data_dir).ok();

            // Initialize DB synchronously in setup (using tokio runtime)
            let db: Result<DatabaseConnection, AppError> = tauri::async_runtime::block_on(async {
                init_database(&app_data_dir).await
            });
            let db = db.expect("Failed to initialize database");

            app.manage(AppState { db });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_bindings() {
        let builder = create_builder();
        builder
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number)
                    .header("// @ts-nocheck\n// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.\n"),
                "../src/renderer/src/lib/bindings.ts",
            )
            .expect("Failed to export TypeScript bindings");
    }
}

